name: sinkpro
description: "WebView App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/sinkprolink.png'
  adaptive_icon_foreground: 'assets/images/sinkprolink.png'
  adaptive_icon_background: '#000024'

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf